### ISSUE TITLE
Support sending metrics from the server instead of the client

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/sdr-metrics-api#20]
The ideal scenario for us to track downloads would be to do so from stacks, which is designed to serve all file requests for SDR content and thus would represent the best place from which to collect metrics (see https://github.com/sul-dlss/stacks/issues/1048).

Unfortunately, ahoy is designed to do two things:
- be installed into a rails app where the user is requesting pages of that same app, and parse events from those requests
- be an API to which browsers can send events via javascript, which include details about a user's browser

Stacks is neither: it's a separate server-side app, where the user's request goes directly to an API to be handled. To get the functionality we want, we'll need to add a new API to this app that supports sending event and visit data directly, and move some of the device detection and other browser-facing logic into stacks itself.

https://github.com/sul-dlss/stacks/pull/1054 handles the stacks side, but it assumed that ahoy would permit requests to its API that include things like device data. Instead, ahoy ignores these parameters because it wants to infer this data itself from the request, so if the request doesn't come from a browser, it fails. We need a new API that doesn't attempt to do that.

**Comment by justinlittman** [comment]
@thatbudakguy Can we just set the `User-Agent` header to mimic the request's `User-Agent` header on the faraday post from stacks to ahoy?

**Comment by thatbudakguy** [comment]
we can, but what can we do about the IP the request originates from? `X-Forwarded-For`, maybe?

**Comment by justinlittman** [comment]
Do we care? We're not recording the actual IP, right?

**Comment by thatbudakguy** [comment]
We are recording an anonymized version of the IP – the final octet is masked (set to zero). We need to do this, because otherwise everyone with the same user agent will be lumped into one visit/session. The "anonymity set" strategy that Ahoy provides combines masked IP with user agent to create a set.

**Comment by thatbudakguy** [comment]
So it looks like [Ahoy checks `ActionDispatch::Request#remote_ip`](https://github.com/ankane/ahoy/blob/f16120bc039ba79c463f0fa3f1b9c402841f3698/lib/ahoy/visit_properties.rb#L100
) when the request comes in, which I believe should look at `X-Forwarded-For`. I'm going to try setting those headers from faraday and see what happens.

**Comment by thatbudakguy** [comment]
It worked: https://github.com/sul-dlss/stacks/pull/1086 seems to do everything we want.
